package searchers

import (
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/cloudformation"
	aw "github.com/deanishe/awgo"
	"github.com/rkoval/alfred-aws-console-services-workflow/awsworkflow"
	"github.com/rkoval/alfred-aws-console-services-workflow/caching"
	"github.com/rkoval/alfred-aws-console-services-workflow/util"
)

type CloudFormationStackSearcher struct{}

func (s CloudFormationStackSearcher) Search(wf *aw.Workflow, query string, session *session.Session, forceFetch bool, fullQuery string) error {
	cacheName := util.GetCurrentFilename()
	entities := caching.LoadCloudformationStackArrayFromCache(wf, session, cacheName, s.fetch, forceFetch, fullQuery)
	for _, entity := range entities {
		s.addToWorkflow(wf, query, session.Config, entity)
	}
	return nil
}

func (s CloudFormationStackSearcher) fetch(session *session.Session) ([]cloudformation.Stack, error) {
	svc := cloudformation.New(session)

	NextToken := ""
	var entities []cloudformation.Stack
	for {
		params := &cloudformation.DescribeStacksInput{}
		if NextToken != "" {
			params.NextToken = aws.String(NextToken)
		}
		resp, err := svc.DescribeStacks(params)
		if err != nil {
			return nil, err
		}

		for _, entity := range resp.Stacks {
			entities = append(entities, *entity)
		}

		if resp.NextToken != nil {
			NextToken = *resp.NextToken
		} else {
			break
		}
	}

	return entities, nil
}

func (s CloudFormationStackSearcher) addToWorkflow(wf *aw.Workflow, query string, config *aws.Config, entity cloudformation.Stack) {
	title := *entity.StackName
	tagName := util.GetCloudFormationTagValue(entity.Tags, "Name")
	// if stack was generated by ElasticBeanstalk and has the generated name, append name tag
	if strings.HasPrefix(title, "awseb-") && tagName != "" {
		title += fmt.Sprintf(" (%s)", tagName)
	}
	subtitle := *entity.Description

	item := util.NewURLItem(wf, title).
		Subtitle(subtitle).
		Arg(fmt.Sprintf("https://%s.console.aws.amazon.com/cloudformation/home?region=%s#/stacks/stackinfo?stackId=%s", *config.Region, *config.Region, *entity.StackId)).
		Icon(awsworkflow.GetImageIcon("cloudwatch"))

	// if stack was generated by ElasticBeanstalk and has the generated name, use the name tag instead
	if strings.HasPrefix(title, "awseb-") && !strings.HasPrefix(query, "awseb-") && tagName != "" {
		item.Match(tagName)
	} else {
		item.Match(title)
	}
}
